# Generated by Django 4.1.5 on 2023-01-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verifycode',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
