# Generated by Django 4.1.5 on 2023-01-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0004_rename_transcationid_purchasedproduct_transactionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedproduct',
            name='modeofpayment',
            field=models.CharField(choices=[('card', 'debit/creditcard'), ('net', 'net banking'), ('upi', 'upi')], default='card', max_length=20),
        ),
    ]
