# Generated by Django 4.1.5 on 2023-01-24 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecapp', '0006_delete_purchasedproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedProduct',
            fields=[
                ('orderid', models.CharField(default='none', max_length=10, primary_key=True, serialize=False)),
                ('paymentid', models.CharField(default='none', max_length=20)),
                ('transactionid', models.CharField(default='none', max_length=20)),
                ('paymentstatus', models.BooleanField(default=False)),
                ('nameonpurchase', models.CharField(default='none', max_length=40)),
                ('dateofpurchase', models.DateField()),
                ('quantity', models.IntegerField()),
                ('modeofpayment', models.CharField(choices=[('card', 'debit/creditcard'), ('net', 'net banking'), ('upi', 'upi')], default='card', max_length=20)),
                ('address', models.CharField(default='nowhere', max_length=200)),
                ('pincode', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('placed', 'placed'), ('shipped', 'shipped'), ('delivered', 'delivered')], default='placed', max_length=20)),
                ('phone', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecapp.product')),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
