# Generated by Django 4.1.7 on 2023-03-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0007_purchasedproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Gifting', (('Hand painted bookmark', 'Hand painted bookmark'), ('Hand painted bottle lamp with cork light', 'Hand painted bottle lamp with cork light'), ('Hand painted teracota diya', 'Hand painted teracota diya'), ('Hand painted jwellary box', 'Hand painted jwellary box'), ('Hand painted decorative trunk', 'Hand painted decorative trunk'))), ('Home utility', (('Handpainted name plated', 'Handpainted name plated'), ('Handpainted key holder', 'Handpainted key holder'), ('Handpainted wooden tray', 'Handpainted wooden tray'), ('Handpainted cups', 'Handpainted cups'), ('Handpainted glass bottles', 'Handpainted glass bottles'), ('Handpainted furnitures', 'Handpainted furnitures'), ('Hand painted jwellary box', 'Hand painted jwellary box'))), ('Home decor', (('Handpainted magnets', 'Handpainted magnets'), ('Handpainted traditional painting', 'Handpainted traditional painting'), ('Handpainted teracota diya', 'Handpainted teracota diya'), ('Handpainted decorative trunk', 'Handpainted decorative trunk')))], default='Hand painted bookmark', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='verifycode',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
