# Generated by Django 4.2 on 2023-05-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0009_paymentdetails_remove_purchasedproduct_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchasedproduct',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchasedproduct',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
