# Generated by Django 4.2 on 2023-05-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0010_orderdetails_amount_purchasedproduct_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='modeofpayment',
            field=models.CharField(choices=[('card', 'debit/creditcard'), ('net', 'net banking'), ('upi', 'upi'), ('cod', 'cash on delivery')], default='cod', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Madhubani painting', 'Madhubani painting'), ('Bottle arts', 'Bottle arts'), ('Name plates', 'Name plates'), ('Wall plates', 'Wall plates')], default='Hand painted bookmark', max_length=100),
        ),
    ]
