# Generated by Django 3.2.20 on 2024-05-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0011_alter_paymentdetails_modeofpayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='trend_score',
            field=models.IntegerField(default=0),
        ),
    ]
